### ISSUE TITLE
Alpha Nycta Spawns - Ragnarok

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#15]
- Definitely need to reduce the spawn amounts of Alpha Nyctas, compared to all other Alphas (Video provided) 
https://i.gyazo.com/ab09af3cab14fb936d1d472d898b2068.gif

**Comment by Decollates** [comment]
Alpha spawns are still extremely high in comparison to other vanilla alphas.

**Comment by bluescapes** [comment]
Making an alpha spawn rarely through mods is a little difficult, without making them piggyback of the spawns of their regular versions. Though, since some of the desired spawn regions don't have alphas in them, I won't do that to preserve those zones.

Their spawn chances are laughably low at the moment, maybe enough so that the spawners fail to recognize the limiters and whatnot I have set?

Piggybacking alpha spawns would quickly fix this issue, but then you'll get alphas in previously unspecified places. Otherwise it'll take a little guess-and-check to get the spawns working properly.
